### ISSUE TITLE
Hiding the clock only work on the main screen

### ISSUE THREAD

**Issue by ItsGosho** [jmalarcon/Win11ClockToggler#16]
When the clock is hidden it is hidden only on the main screen, but the rest screens still visualize it.

**Comment by jmalarcon** [comment]
Hi:

If you switch the option "Secondary" to "Hide", they are hidden. Just try it:

![image](https://user-images.githubusercontent.com/1775322/203831499-1de7cd26-d553-4e5d-9214-e9b447b32370.png)

If you've already switched it, then, what version of Windows 11 are you using? If you're on the dev/preview channel, I don't support that. I need to analyze the taskbar structure every time a new version is released if it doesn't work, and make the appropriate changes, so I only do that on officially released versions.
