### ISSUE TITLE
System Tray bug

### ISSUE THREAD

**Issue by thesaurae** [jmalarcon/Win11ClockToggler#2]
![image](https://user-images.githubusercontent.com/100371174/162884678-a110e392-b92f-406c-bfe6-a67a25edbd4d.png)

**Comment by jmalarcon** [comment]
Any context on that? It shouldn't happen, so I need to know exactly when this happen, if it worked first but after a while you got that, etc.

Please, try to write at least a "Hello" and a short explanation the next time. Thanks.

**Comment by jmalarcon** [comment]
Hi:

I need the exact version of Windows that you're using. I can confirm that on the latest version of Windows 11 with the latest security patches (OS build 22000.613) and before that one, it works as expected.

Press `WIN`+`I` and go to  `System > About` and in the `Windows Specifications` section tell me the exact version you're using. If it's a preview version maybe something has changed in the structure of Windows for the taskbar.

Thanks
