### ISSUE TITLE
[BUG] The notification area and/or the Date/Time controls have not been found. 

### ISSUE THREAD

**Issue by markallisongit** [jmalarcon/Win11ClockToggler#22]
**Describe the bug**
When I click Toggle Visibility I get this error:

```
---------------------------
Problem!
The notification area and/or the Date/Time controls have not been found. This program is designed for Windows 11 (although it works with Windows 10 too).  Maybe you're using a newer version of Windows. 

Or maybe your version of Windows 11 is newer and the layout for building the taskbar has been changed.

Please, contact me through GitHub (https://github.com/jmalarcon/Win11ClockToggler) 

and let me know about this issue. Thanks!
```

**Exact Windows version and language**
Windows 11 Pro 22H2 Build 22621.1413 UK Locale

**Expected behavior**
Hide the clock!

**Current behavior**
When I click Toggle Visibility, I get the error above

**Screenshots**
![image](https://user-images.githubusercontent.com/20219805/226101217-7c600954-27a4-4ef9-8238-8fa8c1b97581.png)

![image](https://user-images.githubusercontent.com/20219805/226101082-79b35496-89cd-49c2-b837-b977b9db12e3.png)

![image](https://user-images.githubusercontent.com/20219805/226101089-f9d4a271-9314-4b50-9baf-d56064e1d583.png)

**Comment by jmalarcon** [comment]
Please, read the big note at the beginning of the readme, and in the application download. And the highlighted message in the community tab. Thanks.
