### ISSUE TITLE
How can i reset it?

### ISSUE THREAD

**Issue by imHamo** [jmalarcon/Win11ClockToggler#3]
what i was looking for is to hide the clock in taskbar and keep everything else
but what happen here the clock still show up but i lost the notificationArea 
![image](https://user-images.githubusercontent.com/79617976/166133956-378cb09a-2c82-477d-acfe-f22f9dd29eda.png)

i'm trying to reset everything to default but no luck i tried all commands so far
Win11ClockToggler /n

is there any way to restore the notificationArea ?

Thanks for hard work!

**Comment by jmalarcon** [comment]
Hi Mohamed:

I'm sorry for the inconvenience. Probably what happened is that, while the clock was hidden, a new icon has appeared in the notification area, making the clock (and part of the notification area) to appear again.

You can reset the toolbar easily by doing this:

- Make sure you have a file explorer open (press `Windows`+`E` at the same time to open one)
- Open the task manager (press `CTRL`+`CAPS`+`ESC` at the same time
- In the window that pops up, look for "Windows Explorer" and press `Restart`:

![image](https://user-images.githubusercontent.com/1775322/166135638-f2e481dd-9083-40a5-b71a-cb3d9eac7216.png)

That's it: it will reset your task bar and keep everything as it was.

Please, take into account that Win11Toggler uses a hacky way to do it's job and sometimes can lead to this kind of situations (specially if one doesn't follow the recommendation in the readme of enabling focus assist).

However I'm now working on a whole new version with a different approach that will be hopefully ready very soon. It will have a nice user interface and a monitor to detect when the things you've hidden are shown again by the system without you knowing it. I think it will fix all this issues.

Thanks

**Comment by imHamo** [comment]
> Hi Mohamed:
> 
> I'm sorry for the inconvenience. Probably what happened is that, while the clock was hidden, a new icon has appeared in the notification area, making the clock (and part of the notification area) to appear again.
> 
> You can reset the toolbar easily by doing this:
> 
> * Make sure you have a file explorer open (press `Windows`+`E` at the same time to open one)
> * Open the task manager (press `CTRL`+`CAPS`+`ESC` at the same time
> * In the window that pops up, look for "Windows Explorer" and press `Restart`:
> 
> ![image](https://user-images.githubusercontent.com/1775322/166135638-f2e481dd-9083-40a5-b71a-cb3d9eac7216.png)
> 
> That's it: it will reset your task bar and keep everything as it was.
> 
> Please, take into account that Win11Toggler uses a hacky way to do it's job and sometimes can lead to this kind of situations (specially if one doesn't follow the recommendation in the readme of enabling focus assist).
> 
> However I'm now working on a whole new version with a different approach that will be hopefully ready very soon. It will have a nice user interface and a monitor to detect when the things you've hidden are shown again by the system without you knowing it. I think it will fix all this issues.
> 
> Thanks

wow i didn't expect to a answer that fast!
thanks for the help and will wait your new updates

Thanks José
